#include "states.hpp"

StateMainMenu Main_Menu;
StateStudentsMenu Students_Menu;
StateCoursesMenu Courses_Menu;
StateRegisterationMenu Registeration_Menu;
StateReportsMenu Reports_Menu;
StateDefaultWorkspace Default_Workspace;
StateAddStudent Add_Student;
StateStudentsList Students_List;
StateAddTheoreticalCourse Add_Theoretical_Course;
StateAddPracticalCourse Add_Practical_Course;
StateCoursesList Courses_List;
StateRemoveStudent Remove_Student;
StateNotificationStudentAddSuccess Notification_Student_Add_Success;
StateNotificationStudentAddFail Notification_Student_Add_Fail;
StateNotificationCourseAddSuccess Notification_Course_Add_Success;
StateNotificationPracticalCourseAddFail Notification_Practical_Course_Add_Fail;
StateNotificationTheoreticalCourseAddFail Notification_Theoretical_Course_Add_Fail;
StateNotificationRemoveStudentPopup Notification_Remove_Student_Popup;
StateNotificationRemoveCoursePopup Notification_Remove_Course_Popup;
StateRemoveCourse Remove_Course;
StateSearchStudent Search_Student;
StateSearchCourse Search_Course;
StateCourseRegister Course_Register;
StateNotificationRegisterSuccess Notification_Register_Success;
StateNotificationRegisterFail Notification_Register_Fail;
StateCourseUnregister Course_Unregister;
StateNotificationUnregisterSuccess Notification_Unregister_Success;
StateGradeEntry Grade_Entry;
StateNotificationGradeEntrySuccess Notification_Grade_Entry_Success;
StateNotificationGradeEntryFail Notification_Grade_Entry_Fail;
StateCourseGrades Course_Grades;
StateRegisterList Register_List;
StateSaveToFile Save_To_File;
StateLoadFromFile Load_From_File;
StateNotificationStudentAddDuplicate Notification_Student_Add_Duplicate;
StateNotificationTheoreticalCourseAddDuplicate Notification_Theoretical_Course_Add_Duplicate;
StateNotificationPracticalCourseAddDuplicate Notification_Practical_Course_Add_Duplicate;
StateInitialCheck Initial_Check;
StateExit Exit;

State *states_table[NUMBER_OF_STATES] = {
	&Main_Menu,
	&Students_Menu,
	&Courses_Menu,
	&Registeration_Menu,
	&Reports_Menu,
	&Default_Workspace,
	&Add_Student,
	&Students_List,
	&Add_Theoretical_Course,
	&Add_Practical_Course,
	&Courses_List,
	&Remove_Student,
	&Notification_Student_Add_Success,
	&Notification_Student_Add_Fail,
	&Notification_Course_Add_Success,
	&Notification_Practical_Course_Add_Fail,
	&Notification_Theoretical_Course_Add_Fail,
	&Notification_Remove_Student_Popup,
	&Notification_Remove_Course_Popup,
	&Remove_Course,
	&Search_Student,
	&Search_Course,
	&Course_Register,
	&Notification_Register_Success,
	&Notification_Register_Fail,
	&Course_Unregister,
	&Notification_Unregister_Success,
	&Grade_Entry,
	&Notification_Grade_Entry_Success,
	&Notification_Grade_Entry_Fail,
	&Course_Grades,
	&Register_List,
	&Save_To_File,
	&Load_From_File,
	&Notification_Student_Add_Duplicate,
	&Notification_Theoretical_Course_Add_Duplicate,
	&Notification_Practical_Course_Add_Duplicate,
	&Initial_Check,
	&Exit
};